<?xml version="1.0"?>
<robot name="challenge_robot" xmlns:xacro="http://www.ros.org/wiki/xacro"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="http://download.ros.org/schema/urdf/urdf.xsd">

  <!-- 1. 定义常量  -->
  <xacro:property name="base_width" value="0.45" />     <!-- 宽度 45cm -->
  <xacro:property name="base_length" value="0.50" />    <!-- 长度 50cm -->
  <xacro:property name="base_height" value="0.10" />    <!-- 高度 10cm -->
  <xacro:property name="wheel_radius" value="0.05" />   <!-- 轮子半径 5cm -->
  <xacro:property name="wheel_width" value="0.02" />    <!-- 轮子宽度 2cm -->
  <xacro:property name="wheel_ygap" value="0.05" />     <!-- 轮子离侧面的距离 -->

  <!-- 2. 材质定义 -->
  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <!-- 3. 底盘链接 (Base Link) -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
    <!-- 手动计算的惯性矩阵 (长方体) -->
    <inertial>
      <mass value="5.0" />
      <inertia 
        ixx="${(1/12)*5.0*(base_width*base_width + base_height*base_height)}" 
        ixy="0.0" 
        ixz="0.0"
        iyy="${(1/12)*5.0*(base_length*base_length + base_height*base_height)}" 
        iyz="0.0"
        izz="${(1/12)*5.0*(base_length*base_length + base_width*base_width)}" />
    </inertial>
  </link>

  <!-- 4. 激光雷达 (Lidar) - 放在底盘前方中心 -->
  <link name="laser_link">
    <visual>
      <geometry>
        <cylinder radius="0.02" length="0.05"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.02" length="0.05"/>
      </geometry>
    </collision>
    <!-- 简化的惯性矩阵 (小质量物体) -->
    <inertial>
      <mass value="0.1" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001" />
    </inertial>
  </link>

  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser_link"/>
    <origin xyz="0.22 0 0.08" rpy="0 0 0"/> <!-- 距离前端3cm，高度8cm -->
  </joint>

  <!-- 激光雷达 Gazebo 插件 - 发布 /scan 话题 -->
  <gazebo reference="laser_link">
    <sensor type="ray" name="laser_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1.0</resolution>
            <min_angle>0</min_angle>
            <max_angle>6.28319</max_angle>
          </horizontal>
          <vertical>
            <samples>1</samples>
            <resolution>1.0</resolution>
            <min_angle>0</min_angle>
            <max_angle>0</max_angle>
          </vertical>
        </scan>
        <range>
          <min>0.1</min>
          <max>12.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="laser_plugin" filename="libgazebo_ros_laser.so">
        <topicName>/scan</topicName>
        <frameName>laser_link</frameName>
      </plugin>
    </sensor>
  </gazebo>

  <!-- 5. 轮子定义宏 (Macro) -->
  <xacro:macro name="wheel" params="prefix x y">
    <link name="${prefix}_wheel">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
        <origin rpy="1.5708 0 0" xyz="0 0 0"/> <!-- 旋转90度 -->
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <origin rpy="1.5708 0 0" xyz="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.5" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
      </inertial>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${x} ${y} ${-base_height/2}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- 6. 实例化四个轮子 -->
  <xacro:wheel prefix="left_front" x="${base_length/2 - wheel_width}" y="${base_width/2 - wheel_ygap}"/>
  <xacro:wheel prefix="right_front" x="${base_length/2 - wheel_width}" y="${-base_width/2 + wheel_ygap}"/>
  <xacro:wheel prefix="left_back" x="${-base_length/2 + wheel_width}" y="${base_width/2 - wheel_ygap}"/>
  <xacro:wheel prefix="right_back" x="${-base_length/2 + wheel_width}" y="${-base_width/2 + wheel_ygap}"/>

  <!-- 7. Gazebo 物理属性 -->
  <gazebo reference="base_link">
    <mu1 value="100.0"/>
    <mu2 value="100.0"/>
    <kp value="10000000.0"/>
    <kd value="10000000.0"/>
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- 为轮子添加摩擦力 -->
  <xacro:macro name="wheel_gazebo" params="prefix">
    <gazebo reference="${prefix}_wheel">
      <mu1 value="1.0"/>
      <mu2 value="1.0"/>
      <fdir1 value="1 0 0"/>
      <slip1 value="0.0"/>
      <slip2 value="0.0"/>
    </gazebo>
  </xacro:macro>

  <xacro:wheel_gazebo prefix="left_front"/>
  <xacro:wheel_gazebo prefix="right_front"/>
  <xacro:wheel_gazebo prefix="left_back"/>
  <xacro:wheel_gazebo prefix="right_back"/>

  <!-- 使用 libgazebo_ros_diff_drive.so ） -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>50.0</updateRate>
      
      <!-- 左右轮关节（支持多轮同侧） -->
      <leftJoint>left_front_wheel_joint</leftJoint>
      <leftJoint>left_back_wheel_joint</leftJoint>
      <rightJoint>right_front_wheel_joint</rightJoint>
      <rightJoint>right_back_wheel_joint</rightJoint>
      
      <!-- 物理参数 -->
      <wheelSeparation>${base_width - 2 * wheel_ygap}</wheelSeparation> <!-- 0.35 m -->
      <wheelDiameter>${2 * wheel_radius}</wheelDiameter> <!-- 0.1 m -->
      
      <!-- ROS 接口 -->
      <commandTopic>/cmd_vel</commandTopic>
      <odometryTopic>/odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_link</robotBaseFrame>
      
      <!-- 发布 odom -> base_link 的 TF -->
      <publishOdomTF>true</publishOdomTF>
    </plugin>
  </gazebo>
  
  <!-- 8. 前向摄像头 (用于视觉识别) -->
<link name="camera_link">
  <visual>
    <geometry>
      <box size="0.02 0.03 0.02"/>
    </geometry>
    <material name="black"/>
  </visual>
  <collision>
    <geometry>
      <box size="0.02 0.03 0.02"/>
    </geometry>
  </collision>
  <inertial>
    <mass value="0.05"/>
    <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
  </inertial>
</link>

<joint name="camera_joint" type="fixed">
  <parent link="base_link"/>
  <child link="camera_link"/>
  <origin xyz="0.24 0 0.08" rpy="0 0 0"/> <!-- 略高于激光雷达 -->
</joint>

<!-- Gazebo 摄像头插件 -->
<gazebo reference="camera_link">
  <sensor type="camera" name="front_camera">
    <update_rate>30.0</update_rate>
    <camera>
      <horizontal_fov>1.047</horizontal_fov> <!-- 60度 -->
      <image>
	<width>640</width>
	<height>480</height>
	<format>R8G8B8</format>
      </image>
      <clip>
	<near>0.1</near>
	<far>10.0</far>
      </clip>
    </camera>
    <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>30.0</updateRate>
      <cameraName>front_camera</cameraName>
      <imageTopicName>/camera/image_raw</imageTopicName>
      <cameraInfoTopicName>/camera/camera_info</cameraInfoTopicName>
      <frameName>camera_link</frameName>
      <hackBaseline>0.07</hackBaseline>
    </plugin>
  </sensor>
</gazebo>

</robot>
